/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SmePreviewSmeIdRouteImport } from './routes/sme-preview.$smeId'
import { Route as DemoSmeRouteImport } from './routes/demo.sme'
import { Route as DemoInvestorRouteImport } from './routes/demo.investor'
import { Route as AppVerificationRouteImport } from './routes/app.verification'
import { Route as AppUploadRouteImport } from './routes/app.upload'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppManualRouteImport } from './routes/app.manual'
import { Route as AppInvestorsRouteImport } from './routes/app.investors'
import { Route as AppIdentityRouteImport } from './routes/app.identity'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppFindInvestorRouteImport } from './routes/app.find-investor'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppSmeShopIdRouteImport } from './routes/app.sme.$shopId'
import { Route as AppReviewUploadIdRouteImport } from './routes/app.review.$uploadId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SmePreviewSmeIdRoute = SmePreviewSmeIdRouteImport.update({
  id: '/sme-preview/$smeId',
  path: '/sme-preview/$smeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSmeRoute = DemoSmeRouteImport.update({
  id: '/demo/sme',
  path: '/demo/sme',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoInvestorRoute = DemoInvestorRouteImport.update({
  id: '/demo/investor',
  path: '/demo/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerificationRoute = AppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppManualRoute = AppManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorsRoute = AppInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityRoute = AppIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppFindInvestorRoute = AppFindInvestorRouteImport.update({
  id: '/find-investor',
  path: '/find-investor',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppSmeShopIdRoute = AppSmeShopIdRouteImport.update({
  id: '/sme/$shopId',
  path: '/sme/$shopId',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewUploadIdRoute = AppReviewUploadIdRouteImport.update({
  id: '/review/$uploadId',
  path: '/review/$uploadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/find-investor': typeof AppFindInvestorRoute
  '/app/history': typeof AppHistoryRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/investors': typeof AppInvestorsRoute
  '/app/manual': typeof AppManualRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/app/verification': typeof AppVerificationRoute
  '/demo/investor': typeof DemoInvestorRoute
  '/demo/sme': typeof DemoSmeRoute
  '/sme-preview/$smeId': typeof SmePreviewSmeIdRoute
  '/app/': typeof AppIndexRoute
  '/app/review/$uploadId': typeof AppReviewUploadIdRoute
  '/app/sme/$shopId': typeof AppSmeShopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/find-investor': typeof AppFindInvestorRoute
  '/app/history': typeof AppHistoryRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/investors': typeof AppInvestorsRoute
  '/app/manual': typeof AppManualRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/app/verification': typeof AppVerificationRoute
  '/demo/investor': typeof DemoInvestorRoute
  '/demo/sme': typeof DemoSmeRoute
  '/sme-preview/$smeId': typeof SmePreviewSmeIdRoute
  '/app': typeof AppIndexRoute
  '/app/review/$uploadId': typeof AppReviewUploadIdRoute
  '/app/sme/$shopId': typeof AppSmeShopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/find-investor': typeof AppFindInvestorRoute
  '/app/history': typeof AppHistoryRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/investors': typeof AppInvestorsRoute
  '/app/manual': typeof AppManualRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/upload': typeof AppUploadRoute
  '/app/verification': typeof AppVerificationRoute
  '/demo/investor': typeof DemoInvestorRoute
  '/demo/sme': typeof DemoSmeRoute
  '/sme-preview/$smeId': typeof SmePreviewSmeIdRoute
  '/app/': typeof AppIndexRoute
  '/app/review/$uploadId': typeof AppReviewUploadIdRoute
  '/app/sme/$shopId': typeof AppSmeShopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/app/alerts'
    | '/app/documents'
    | '/app/find-investor'
    | '/app/history'
    | '/app/identity'
    | '/app/investors'
    | '/app/manual'
    | '/app/profile'
    | '/app/settings'
    | '/app/upload'
    | '/app/verification'
    | '/demo/investor'
    | '/demo/sme'
    | '/sme-preview/$smeId'
    | '/app/'
    | '/app/review/$uploadId'
    | '/app/sme/$shopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/alerts'
    | '/app/documents'
    | '/app/find-investor'
    | '/app/history'
    | '/app/identity'
    | '/app/investors'
    | '/app/manual'
    | '/app/profile'
    | '/app/settings'
    | '/app/upload'
    | '/app/verification'
    | '/demo/investor'
    | '/demo/sme'
    | '/sme-preview/$smeId'
    | '/app'
    | '/app/review/$uploadId'
    | '/app/sme/$shopId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/app/alerts'
    | '/app/documents'
    | '/app/find-investor'
    | '/app/history'
    | '/app/identity'
    | '/app/investors'
    | '/app/manual'
    | '/app/profile'
    | '/app/settings'
    | '/app/upload'
    | '/app/verification'
    | '/demo/investor'
    | '/demo/sme'
    | '/sme-preview/$smeId'
    | '/app/'
    | '/app/review/$uploadId'
    | '/app/sme/$shopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DemoInvestorRoute: typeof DemoInvestorRoute
  DemoSmeRoute: typeof DemoSmeRoute
  SmePreviewSmeIdRoute: typeof SmePreviewSmeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sme-preview/$smeId': {
      id: '/sme-preview/$smeId'
      path: '/sme-preview/$smeId'
      fullPath: '/sme-preview/$smeId'
      preLoaderRoute: typeof SmePreviewSmeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sme': {
      id: '/demo/sme'
      path: '/demo/sme'
      fullPath: '/demo/sme'
      preLoaderRoute: typeof DemoSmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/investor': {
      id: '/demo/investor'
      path: '/demo/investor'
      fullPath: '/demo/investor'
      preLoaderRoute: typeof DemoInvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/verification': {
      id: '/app/verification'
      path: '/verification'
      fullPath: '/app/verification'
      preLoaderRoute: typeof AppVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manual': {
      id: '/app/manual'
      path: '/manual'
      fullPath: '/app/manual'
      preLoaderRoute: typeof AppManualRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investors': {
      id: '/app/investors'
      path: '/investors'
      fullPath: '/app/investors'
      preLoaderRoute: typeof AppInvestorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identity': {
      id: '/app/identity'
      path: '/identity'
      fullPath: '/app/identity'
      preLoaderRoute: typeof AppIdentityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/find-investor': {
      id: '/app/find-investor'
      path: '/find-investor'
      fullPath: '/app/find-investor'
      preLoaderRoute: typeof AppFindInvestorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sme/$shopId': {
      id: '/app/sme/$shopId'
      path: '/sme/$shopId'
      fullPath: '/app/sme/$shopId'
      preLoaderRoute: typeof AppSmeShopIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review/$uploadId': {
      id: '/app/review/$uploadId'
      path: '/review/$uploadId'
      fullPath: '/app/review/$uploadId'
      preLoaderRoute: typeof AppReviewUploadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFindInvestorRoute: typeof AppFindInvestorRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppIdentityRoute: typeof AppIdentityRoute
  AppInvestorsRoute: typeof AppInvestorsRoute
  AppManualRoute: typeof AppManualRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppVerificationRoute: typeof AppVerificationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppReviewUploadIdRoute: typeof AppReviewUploadIdRoute
  AppSmeShopIdRoute: typeof AppSmeShopIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFindInvestorRoute: AppFindInvestorRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppIdentityRoute: AppIdentityRoute,
  AppInvestorsRoute: AppInvestorsRoute,
  AppManualRoute: AppManualRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUploadRoute: AppUploadRoute,
  AppVerificationRoute: AppVerificationRoute,
  AppIndexRoute: AppIndexRoute,
  AppReviewUploadIdRoute: AppReviewUploadIdRoute,
  AppSmeShopIdRoute: AppSmeShopIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DemoInvestorRoute: DemoInvestorRoute,
  DemoSmeRoute: DemoSmeRoute,
  SmePreviewSmeIdRoute: SmePreviewSmeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
